---

- hosts: jenkins-server
  sudo: true
  roles:
    - jenkins

- hosts: wiki-server
  sudo: true
  vars:
    tracHomeDir: /home/trac
    tracConfigDir: /home/trac/trac_config
  roles:
    - python
    - trac
