---
  - name: Installing Trac
    easy_install: name=trac
  - name: Creating Trac user
    user: name=trac
  - name: Creating Trac configuration
    command: trac-admin {{ tracConfigDir }} initenv dbp sqlite:db/trac.db creates={{ tracConfigDir }}
  - name: Changing ownership of Trac config
    command: chown -R trac {{ tracConfigDir }}
  - name: Changing group of Trac config
    command: chgrp -R trac {{ tracConfigDir }}
  - name: Starting Trac wiki on port 80
    command: tracd --user=trac -s -d --pidfile={{ tracHomeDir }}/trac.pid -e {{ tracConfigDir }}
