---
  - easy_install: name=trac
  - command: creates={{ tracConfigDir }} trac-admin {{ tracConfigDir }} initenv dbp sqlite:db/trac.db
  - command: chown -R trac {{ tracConfigDir }}
  - command: chgrp -R trac {{ tracConfigDir }}
  - name: Starting Trac wiki on port 80
    command: tracd --user=trac -d --pidfile={{ tracHomeDir }}/trac.pid -e {{ tracConfigDir }}
