---
  - name: Add Jenkins repo key
    apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
  - name: Add Jenkins repo
    apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present
  - name: Install Jenkins
    apt: pkg=jenkins state=present
